# Generated by Django 4.2.6 on 2023-11-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_alter_todo_finish_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="expect_finish_date",
            field=models.DateTimeField(help_text="预计完成时间"),
        ),
    ]
