version: '3'

services:
    mongodb:
        image: mongo:5.0.7
        restart: unless-stopped
        env_file: ./.env
        container_name: mongodb
        ports:
          - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
        volumes:
          - ./data:/data/db
        environment:
          - MONGO_INITDB_ROOT_USERNAME=$DB_USER
          - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
          # - MONGO_INITDB_DATABASE=todo
          # - MONGO_USERNAME=todo_admin
          # - MONGO_PASSWORD=drq12345!
        # restart: always
    
    # mongo-express:
    #     image: mongo-express
    #     env_file: ./.env
    #     container_name: mongo-express
    #     restart: always
    #     ports:
    #       - '8081:8081'
    #     environment:
    #       - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USER
    #       - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
    #       - ME_PORT=$MONGODB_DOCKER_PORT
    #       - ME_CONFIG_MONGODB_SERVER=mongodb

    
    web:
      depends_on:
        - mongodb
      build: .
      command: node index.js
      env_file: ./.env
      volumes:
        - .:/app
        - /app/node_modules
      ports:
        - $PORT:$PORT
      environment:
        - DB_HOST=mongodb
        - DB_USER=$MONGODB_USER
        - DB_PASSWORD=$MONGODB_PASSWORD
        - DB_NAME=$MONGODB_DATABASE
        - DB_PORT=$MONGODB_DOCKER_PORT
      stdin_open: true
      tty: true
      # environment:
      #   - CONNECTIONSTRING=mongodb://localhost:27017/todo -u todo_admin -p drq12345!
      
      